version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
  - package-ecosystem: "npm"
    directory: "/"
    schedule: "now"
      interval: "daily"
    open-pull-requests-limit: 1000000000000
