**'"{ "Manifest: ENERGY_manifests'@ZachryTylerWood'@Administrator'@it'.git'.it'.github.gist'@.github.com/gists/secrets/BITORE/'('('C')')'('R')')'"'' :'':'
  '-'' '**\*'.dist'@checksuite'@https://www.bitore.net/.moonfruit.org :'@A.P.?I**\*root*Base=content:encoding=$:mk.dir=:src/code.sit=: "$' 'Obj'"' '='' '"new=='":, ''
  - lib/**/*
  - middleware/*
  - middleware/**/*
  - tests/*
  - tests/**/*
  - stylesheets/*
  - stylesheets/**/*
  - script/*
  - script/**/*
  - components/*
  - components/**/*
  - pages/*
  - pages/**/***":," }":,**'"
