
مندمجة
TwitchPlaysBF2 دمج 11 تلتزم رئيسي من قائمة الاصدقاء on 9 Mar
Conversation 0
Commits 11
Checks 0
Files changed 11
محادثة
TwitchPlaysBF2
تضمين التغريدة TwitchPlaysBF2 علق on 9 Mar
لم يتم تقديم وصف.

أضاف TwitchPlaysBF2 11 التزامًا 5 months ago
تضمين التغريدة
temp
31ad1d5
تضمين التغريدة
temp2
0c64bcf
تضمين التغريدة
Minor renamings
56dab52
تضمين التغريدة
temp
233bf8d
تضمين التغريدة
Merge branch 'main' into friendlist
186e560
تضمين التغريدة
Fix error by incorrect redcuer usage
7bc292c
تضمين التغريدة
Minor rename
174bff5
تضمين التغريدة
Fix NRE
134d138
تضمين التغريدة
Refactor friend persistence: 
44a3edc
تضمين التغريدة
Introduce offline friends
a07897d
تضمين التغريدة
Improve friendlist, rename model
7229149
تضمين التغريدة تم دمج TwitchPlaysBF2f78b54d في 
