name: Node set up composite

description: Will set up Node and install all packages by caching node_modules

runs:
  using: 'composite'
  steps:
    - name: Cache node_modules
      uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package*.json') }}

    - name: Setup node
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      with:
        node-version: '16.17.0'
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm install --prefer-offline --no-audit --ignore-scripts
