name: Browser Tests

on:
  workflow_dispatch:
  push:

jobs:
  see_if_should_skip:
    continue-on-error: true
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@36feb0d8d062137530c2e00bd278d138fe191289
        with:
          cancel_others: 'false'
          github_token: ${{ github.token }}
          paths: '[".github/workflows/browser-test.yml","assets/**", "content/**", "data/**", "includes/**", "javascripts/**", "jest-puppeteer.config.js", "jest.config.js", "layouts/**", "lib/**", "middleware/**", "package-lock.json", "package.json", "server.js", "translations/**", "webpack.config.js"]'
  build:
    needs: see_if_should_skip
    if: ${{ needs.see_if_should_skip.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Install
        uses: ianwalter/puppeteer@12728ddef82390d1ecd4732fb543f62177392fbb
        with:
          args: npm ci

      - name: Test
        uses: ianwalter/puppeteer@12728ddef82390d1ecd4732fb543f62177392fbb
        with:
          args: npm run browser-test
