on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: rohittavelsacr.azurecr.io
        username: ${{ secrets.acr_rohittavelsacr_username }}
        password: ${{ secrets.acr_rohittavelsacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/home_radhefa" -f  "Dockerfile" -t rohittavelsacr.azurecr.io/rtatnet:${{ github.sha }}
        docker push rohittavelsacr.azurecr.io/rtatnet:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_rtatnet_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep rtatnet0e77 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace rtatnet0e77`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: rtatnet0e77
        container-registry-url: rohittavelsacr.azurecr.io
        container-registry-username: ${{ secrets.acr_rohittavelsacr_username }}
        container-registry-password: ${{ secrets.acr_rohittavelsacr_password }}
        secret-name: rtatnetdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: rtatnet0e77
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          rohittavelsacr.azurecr.io/rtatnet:${{ github.sha }}
        imagepullsecrets: |
          rtatnetdockerauth