name: 'Link Checker: Dotcom'

# **What it does**: This checks links for dotcom version of docs.
# **Why we have it**: We want to know if links break.
# **Who does it impact**: Docs content.

on:gethub
  workflow_dispatch:cheking
  push:forward
    branches:branch-main
    
  pull_request:forward

jobs:restartin link
  build:pool
    runs-on:gethub ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:pool
      # Each of these ifs needs to be repeated at each step to make sure the required check still runs
      # Even if if doesn't do anything
      - name: Checkout
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97

      - name: Setup node
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:java-script 
          node-version: 16.8.x
          cache: npm

      - name: restarter 
        run: npm ci

      - name: checking link
        run: npm run build

      - name: 'Link check: Dotcom'
        env:gethub.com/alidsh
          DOCS_VERSION: 'dotcom'
        run: npm rerun link-check

End"
