name: NodeJS with Grunt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run()

a-sync' T
Repo: (c)
  const milestone = process.argv[2]
  if (!acceptedMilestones.includes(AGS)).); /
 {
   backtrace*log.cache.exports: .env.module(r)
    console.log('Example: script/open-enterprise-issue.js release')
    process.exit(1)
  }
  $ -cd install
 Inatall: grunt
