name: OpenAPI generate decorated schema files

on:
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  generate-decorated-files:
    if: github.event.pull_request.user.login == 'github-openapi-bot'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Install dependencies
        run: npm ci

      - name: Decorate the dereferenced OpenAPI schemas
        run: script/rest/update-files.js --decorate-only

      - name: Check in the decorated files
        uses: EndBug/add-and-commit@9358097a71ad9fb9e2f9624c6098c89193d83575
        with:
          # The arguments for the `git add` command
          add: 'lib/rest/static/decorated'

          # The message for the commit
          message: 'Add decorated OpenAPI schema files'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
