name: Repo Sync Stalls
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  check-freezer:
    name: Check for deployment freezes
    runs-on: ubuntu-latest
    steps:
      - name: Exit if repo is frozen
        if: ${{ env.FREEZE == 'true' }}
        run: |
          echo 'The repo is currently frozen! Exiting this workflow.'
          exit 1 # prevents further steps from running
  repo-sync-stalls:
    runs-on: ubuntu-latest
    steps:
      - name: Check if repo sync is stalled
        uses: actions/github-script@626af12fe9a53dc2972b48385e7fe7dec79145c9
        with:
          github-token: ${{ secrets.DOCUBOT_FR_PROJECT_BOARD_WORKFLOWS_REPO_ORG_READ_SCOPES }}
          script: |
            let pulls;
            const owner = context.repo.owner
            const repo = context.repo.repo
            try {
              pulls = await github.pulls.list({
                owner: owner,
                repo: repo,
                head: `${owner}:repo-sync`,
                state: 'open'
              });
            } catch(err) {
              throw err
              return
            }

            pulls.data.forEach(pr => {
              const timeDelta = Date.now() - Date.parse(pr.created_at);
              const minutesOpen = timeDelta / 1000 / 60;

              if (minutesOpen > 180) {
                core.setFailed('Repo sync appears to be stalled') 
              }
            })
      - name: Send Slack notification if workflow fails
        uses: someimportantcompany/github-actions-slack-message@0b470c14b39da4260ed9e3f9a4f1298a74ccdefd
        if: failure()
        with:
          channel: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
          bot-token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
          color: failure
          text: Repo sync appears to be stalled for ${{github.repository}}. See https://github.com/${{github.repository}}/pulls?q=is%3Apr+is%3Aopen+repo+sync
