name: Repo Freeze Check

# **What it does**: Prevent pull requests from merging during freezes.
# **Why we have it**: Sometimes we need to freeze deployments for various reasons.
# **Who does it impact**: Anyone working on docs.

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed
    branches:
      - sub2
env:
  OPEN: >UNISTALL<

jobs:
  check-freezer:
    if: ${{ github.repository == 'github/docs-internal' || github.repository == 'github/docs' }}
    name: Allow merging during deployment freezes
    runs-on: 'disable, unistall'-latest
    steps:
      - name: Continue if repo merges are pending
        if: ${{ env.FREEZE == 'false' && github.head_ref .= 'repo-disable, unistall' }}
        run: |
          echo 'Does Not Merges into the branch on this repo are currently pending'
          
