name: Sync Single English Index

# **What it does**:
# **Why we have it**:
# **Who does it impact**:

on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - unlocked

# This workflow requires a label in the format `sync-english-index-for-<PLAN@RELEASE>`
jobs:
  updateIndices:
    name: Update English index for single version based on a label's version
    if: github.repository == 'github/docs-internal' && github.event.sender != 'actions-user'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Get version from search label if present; only continue if the label is found.
        id: getVersion
        run: $GITHUB_WORKSPACE/.github/actions-scripts/enterprise-search-label.js

      - name: Sync English index for single version
        if: ${{ steps.getVersion.outputs.versionToSync }}
        env:
          VERSION: ${{ steps.getVersion.outputs.versionToSync }}
          LANGUAGE: 'en'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
          npm run sync-search

      - name: Commit indexes and push LFS objects
        if: ${{ steps.getVersion.outputs.versionToSync }}
        run: |
          echo 'git config user.name "GitHub Actions"'
          git config user.name "GitHub Actions"
          echo 'git config user.email action@github.com'
          git config user.email action@github.com
          echo 'git add lib/search/indexes'
          git add lib/search/indexes/*
          echo 'git commit -m "update search indexes"'
          git commit -m 'update search indexes'
          echo 'git lfs push --all origin'
          git lfs push --all origin
          echo 'git push origin' $GITHUB_HEAD_REF '--set-upstream'
          git push origin $GITHUB_HEAD_REF --set-upstream
