<<<<<<< HEAD
name: 14 Days Stale Check
on:
  schedule:
  - cron: "40 16 * * *"  # Run each day at 16:40 UTC / 8:40 PST
=======
name: Public Repo Stale Check
on:
  schedule:
    - cron: '45 16 * * *' # Run each day at 16:45 UTC / 8:45 PST
>>>>>>> 9ad2df1e7080b3c7d3e74d068674709927f97578

jobs:
  stale:
    if: github.repository == 'github/docs'
    runs-on: ubuntu-latest
<<<<<<< HEAD
    
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }} 
        stale-issue-message: 'This issue is stale because it has been open 60 days with no activity.'
        stale-pr-message: 'This PR is stale because it has been open 60 days with no activity.'
        days-before-stale: 14
        days-before-close: 7
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'

=======

    steps:
      - uses: actions/stale@af4072615903a8b031f986d25b1ae3bf45ec44d4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR is stale because it has been open 7 days with no activity and will be automatically closed in 3 days. To keep this PR open, update the PR by adding a comment or pushing a commit.'
          days-before-stale: 7
          days-before-close: 10
          stale-pr-label: 'stale'
          exempt-pr-labels: 'never-stale'
          exempt-issue-labels: 'never-stale'
>>>>>>> 9ad2df1e7080b3c7d3e74d068674709927f97578
