name: First responder docs-content
on:
  issues:
    types: [reopened, opened]

jobs:
  triage_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Label new issues with docs-content-fr
      uses: andymckay/labeler@v1.0.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        add-labels: "triage"
    - name: Triage to project board
      uses: konradpabjan/actions-add-new-issue-to-column@v1.1
      with:
        action-token: ${{ secrets.GITHUB_TOKEN }}
        project-url: "https://github.com/github/docs/projects/1"
        column-name: "Triage"
